### PR TITLE
Show a moon when night time

### PR DESCRIPTION
**Pull request by Luki120**
This will prob get closed, but worth a shot. Show a moon when night time, tested and works great (:

### CODE REVIEW

**Comment by camieeh** [comment]
the only reason i’d have to close this is your direct assumption of me to do so, but since this ain’t a bad addition i won’t of course

i wish you’d act normal towards me

**Comment by Luki120** [comment]
Sorry about that, thanks for merging

**Comment by Luki120** [comment]
Hey, idk how can I test it because for some reason I never get "Sunny" or "Clear" conditions lol, I only get Mostly Sunny/Clear, which seem more common ig. Imo you should keep the moon for that condition as well, since it doesn't really make sense to see a cloud with a sun in the night

**Comment by camieeh** [comment]
then i would have to replace all the emojis that have part of the sun in it with the moon which won’t work

works fine 😚
DF570BC5-7706-4F9D-A2DB-4E4EDE8DF794

**Comment by Luki120** [comment]
~~What happened with Lobelias btw? It ain't here or your repo. Also I could use some help if you don't mind, I'm making a music player and adding it to the CSNotificationAdjunctListViewController class stack view, but I can't set a height constraint because the stack view's height doesn't resize if I do that so the Axon cells get cut off. Lobelias didn't have this problem. What can I do to fix it? :')~~

~~Actually nvm, I think I found the solution to all my problems haha, I'll just add it to the coversheet and lower down the notifications~~

Oh well frick, it wouldn't scroll with notifications then

**Comment by camieeh** [comment]
it has reached its end of life fully now, not being maintained anymore

talk to me on discord if you need further help

**Pull request merged**
